### ISSUE TITLE
360 degree fisheye camera image?

### ISSUE THREAD

**Issue by Mariusmarten** [Dtananaev/CarlaFSD#1]
Hi, nice project! Do you think it would be possible to obtain a 360-degree image with the code you provide here? And do you think one could accurately recover the camera intrinsics of that image?

**Comment by Dtananaev** [comment]
1. Concerning intrinsics: you can set your intrinsics which you want to simulate, and camera will be simulated according to them. You may check that camera models initialized from field of view, but by default they can be initialized with intrinsic parameters of your wish. You may need to change code so that the camera projection initialized from intrinsic.
for example:
```python
from carla_fsd.camera_fisheye.camera_models.equidistant_projection import EquidistantProjection
fisheye_projection =EquidistantProjection(fx=300, fy=300, cx=600 cy=400, k0=0, k1=0, k2=0, k3=0, k4=0)
```

3. For full 360 view it is necessary to add one more pinhole, so that you can have 360 view. Current implementation has 5 pinhole cube therefore it can represent 270 degrees views. See https://medium.com/@d.d.tananaev/unleashing-the-power-of-fish-eye-cameras-in-carla-simulator-abb7ab5bc147

**Comment by Mariusmarten** [comment]
Thank you very much for the helpful response! I will close this issue as solved.
