### ISSUE TITLE
Overflow in LenseDistortion.undistorsion function

### ISSUE THREAD

**Issue by Critaek** [Dtananaev/CarlaFSD#3]
Hi, thanks for the model!

I found what I think is a bug in the LensDistortion class.
When calling the undistortion function, the loop makes it so that the numbers will get bigger and bigger and get to the point where they are NaN. This only happens for values of k0, k1, k4 which are NOT zero or really close to it.

To replicate the problem simply call python -m carla_fsd.camera_fisheye.drive with values of k0, k1, k4 > 0 (even one of them will cause issues). 
The call stack is:
-drive.py: line 167 (where the FisheyeCamera is initialized)
--fisheye_camera.py: line 189 (self.compute_mapping() call)
---fisheye_camera.py: line 204 (projection_model.from_2d_to_3d)
----equidistant_projection.py: line 179 (self.lense_distortion.undistortion(dist_x, dist_y))

I am not sure if that's just my problem or it was not intended to be used with values > 0 or close to it.
For reference I tried different values, mainly I would like to use k0 = 0.48 (the rest is 0).

I am not sure if I should just lower the number of iterations or if there is actually a problem with the code.

Thanks in advance!

**Comment by Dtananaev** [comment]
Hi, sorry for delayed response. I checked equations they seems ok, the problem you could have related to numerics. Usually distortion coefficients should be very small  e.g. k0=0.01 k1=-0.002 etc. because the main lens distortion already modeled with equidistant ray model. However if you try to use bigger coefficients e.g. k =0.1 and higher you will start have problems with numerics. In real cameras this model usually works. If precision is not sufficient you may need to change the way how you model your lenses e.g. Scaramuzza [1] model is quite precise, but demands to compute high order polynomial.  

P.S. Lowering number of iterations is not the way to go, because you just receive worse approximation of your lens distortion.

[1] Davide Scaramuzza, Agostino Martinelli, and Roland Siegwart. A toolbox for easily calibrating omnidirectional cameras. In Intelligent Robots and Systems, 2006 IEEE/RSJ International Conference on, pages 5695–5701. IEEE, 2006
